# docker-compose up
version: '3'
services:
  mamuru_bot:
    build: .
    image: mamuru_bot-img
    container_name: mamuru_bot-container
    working_dir: /work
    volumes:
      - ./:/work
    ports:
      - "8888:8888"
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root -b localhost